# Generated by Django 4.2.7 on 2025-07-22 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medication', '0001_initial'),
        ('healthcare', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sideeffect',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_side_effects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sideeffect',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_effects', to='medication.medication'),
        ),
        migrations.AddField(
            model_name='sideeffect',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_side_effects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_provider_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medication_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='medication.medication'),
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicationintake',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='medication.medication'),
        ),
        migrations.AddField(
            model_name='medicationintake',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_intakes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medication',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications', to='healthcare.condition'),
        ),
        migrations.AddField(
            model_name='medication',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_created_medications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medication',
            name='medical_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medication_medications', to='healthcare.medicalrecord'),
        ),
        migrations.AddField(
            model_name='medication',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medication',
            name='prescriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_prescribed_medications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medication',
            name='prescription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication', to='medication.prescription'),
        ),
        migrations.AddField(
            model_name='medication',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_medications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='druginteraction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='druginteraction',
            name='medication_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_a', to='medication.medication'),
        ),
        migrations.AddField(
            model_name='druginteraction',
            name='medication_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_b', to='medication.medication'),
        ),
        migrations.AddField(
            model_name='druginteraction',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adherencerecord',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adherence_records', to='medication.medication'),
        ),
        migrations.AddField(
            model_name='adherencerecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adherence_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='druginteraction',
            unique_together={('medication_a', 'medication_b', 'patient')},
        ),
    ]
