# Generated by Django 4.2.7 on 2025-08-19 14:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='adherence_goal',
            field=models.FloatField(default=0.9),
        ),
        migrations.AddField(
            model_name='medication',
            name='effectiveness_ratings',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='medication',
            name='is_rare_condition_med',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medication',
            name='side_effects_history',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='medication',
            name='smart_reminders_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='MedicationAdherence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('scheduled_time', models.DateTimeField()),
                ('taken', models.BooleanField()),
                ('taken_time', models.DateTimeField(blank=True, null=True)),
                ('effectiveness_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('mood_before', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('mood_after', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('symptoms_before', models.JSONField(default=list)),
                ('symptoms_after', models.JSONField(default=list)),
                ('side_effects', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('missed_reason', models.CharField(blank=True, choices=[('forgot', 'Forgot to take it'), ('side_effects', 'Experienced side effects'), ('feeling_better', 'Feeling better'), ('ran_out', 'Ran out of medication'), ('travel', 'Traveling/not at home'), ('cost', 'Cost concerns'), ('other', 'Other reason')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adherence_records', to='medication.prescription')),
            ],
            options={
                'ordering': ['-scheduled_time'],
                'unique_together': {('prescription', 'scheduled_time')},
            },
        ),
    ]
