# Generated by Django 4.2.7 on 2025-08-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='emergency_contact_relationship',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='anonymous_analytics_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='anonymous_analytics_consent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='data_retention_consent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='data_retention_consent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='marketing_communications_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='marketing_communications_consent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='provider_data_sharing_consent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='provider_data_sharing_consent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
