# Generated by Django 4.2.7 on 2025-08-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_patientprofile_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='email_appointment_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='email_health_records',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='email_medication_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='email_research_updates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='in_app_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='push_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='smartwatch_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='sms_appointment_reminders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='sms_emergency_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='sms_medication_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='consent_type',
            field=models.CharField(choices=[('TERMS_OF_SERVICE', 'Terms of Service'), ('PRIVACY_NOTICE', 'HIPAA Privacy Notice'), ('MEDICATION_MONITORING', 'Medication Adherence Monitoring'), ('VITALS_MONITORING', 'Vitals Monitoring'), ('RESEARCH_PARTICIPATION', 'Research Participation'), ('DATA_SHARING', 'Data Sharing'), ('CAREGIVER_ACCESS', 'Caregiver Access Authorization'), ('PHI_HANDLING', 'PHI Handling Agreement'), ('IDENTITY_VERIFICATION', 'Identity Verification'), ('PROVIDER_DATA_SHARING', 'Provider Data Sharing'), ('MARKETING_COMMUNICATIONS', 'Marketing Communications'), ('DATA_RETENTION', 'Data Retention'), ('ANONYMOUS_ANALYTICS', 'Anonymous Analytics')], max_length=50),
        ),
    ]
