# Generated by Django 4.2.7 on 2025-07-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_session_token_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentrecord',
            name='consent_type',
            field=models.CharField(choices=[('TERMS_OF_SERVICE', 'Terms of Service'), ('PRIVACY_NOTICE', 'HIPAA Privacy Notice'), ('TELEMEDICINE_SERVICES', 'Telemedicine Services'), ('MEDICATION_MONITORING', 'Medication Adherence Monitoring'), ('VITALS_MONITORING', 'Vitals Monitoring'), ('RESEARCH_PARTICIPATION', 'Research Participation'), ('DATA_SHARING', 'Data Sharing'), ('CAREGIVER_ACCESS', 'Caregiver Access Authorization'), ('PHI_HANDLING', 'PHI Handling Agreement'), ('IDENTITY_VERIFICATION', 'Identity Verification')], max_length=30),
        ),
    ]
