# Generated by Django 4.2.7 on 2025-07-14 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_pharmaceuticaltenant_user_account_locked_until_and_more'),
    ]

    operations = [
    ]
