# Generated by Django 4.2.7 on 2025-07-22 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fhir', '0001_initial'),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthtopictag',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_topics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='community.communityevent'),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_attendances', to='fhir.fhirpatient'),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='communityresource',
            index=models.Index(fields=['title'], name='community_c_title_69732e_idx'),
        ),
        migrations.AddIndex(
            model_name='communityresource',
            index=models.Index(fields=['created_at'], name='community_c_created_8e9131_idx'),
        ),
        migrations.AddIndex(
            model_name='communityresource',
            index=models.Index(fields=['updated_at'], name='community_c_updated_2ea337_idx'),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='community.communitygroup'),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='health_topics',
            field=models.ManyToManyField(blank=True, related_name='posts', to='community.healthtopictag'),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_posts', to='fhir.fhirpatient'),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitynotification',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='community.communitycomment'),
        ),
        migrations.AddField(
            model_name='communitynotification',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='community.communityevent'),
        ),
        migrations.AddField(
            model_name='communitynotification',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='community.communitygroup'),
        ),
        migrations.AddField(
            model_name='communitynotification',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_notifications', to='fhir.fhirpatient'),
        ),
        migrations.AddField(
            model_name='communitynotification',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='community.communitypost'),
        ),
        migrations.AddField(
            model_name='communitynotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitymembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='community.communitygroup'),
        ),
        migrations.AddField(
            model_name='communitymembership',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_memberships', to='fhir.fhirpatient'),
        ),
        migrations.AddField(
            model_name='communitymembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='health_topics',
            field=models.ManyToManyField(blank=True, related_name='groups', to='community.healthtopictag'),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='verified_healthcare_experts',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'provider'}, related_name='expert_in_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communityevent',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communityevent',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='community.communitygroup'),
        ),
        migrations.AddField(
            model_name='communitycomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitycomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community.communitycomment'),
        ),
        migrations.AddField(
            model_name='communitycomment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_comments', to='fhir.fhirpatient'),
        ),
        migrations.AddField(
            model_name='communitycomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.communitypost'),
        ),
        migrations.AddField(
            model_name='communityaccessibilitysetting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_accessibility', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='healthtopictag',
            index=models.Index(fields=['name'], name='community_h_name_0b3d1c_idx'),
        ),
        migrations.AddIndex(
            model_name='healthtopictag',
            index=models.Index(fields=['is_condition'], name='community_h_is_cond_7cbcc8_idx'),
        ),
        migrations.AddIndex(
            model_name='healthtopictag',
            index=models.Index(fields=['is_treatment'], name='community_h_is_trea_4be5d1_idx'),
        ),
        migrations.AddIndex(
            model_name='healthtopictag',
            index=models.Index(fields=['is_medication'], name='community_h_is_medi_8bf476_idx'),
        ),
        migrations.AddIndex(
            model_name='eventattendee',
            index=models.Index(fields=['event'], name='community_e_event_i_b2c162_idx'),
        ),
        migrations.AddIndex(
            model_name='eventattendee',
            index=models.Index(fields=['user'], name='community_e_user_id_ed80b8_idx'),
        ),
        migrations.AddIndex(
            model_name='eventattendee',
            index=models.Index(fields=['status'], name='community_e_status_435834_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventattendee',
            unique_together={('event', 'user')},
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['group'], name='community_c_group_i_1edc97_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['author'], name='community_c_author__b803d7_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['created_at'], name='community_c_created_9200f5_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['status'], name='community_c_status_c8bd4c_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['post_type'], name='community_c_post_ty_5fdf6c_idx'),
        ),
        migrations.AddIndex(
            model_name='communitynotification',
            index=models.Index(fields=['user'], name='community_c_user_id_685929_idx'),
        ),
        migrations.AddIndex(
            model_name='communitynotification',
            index=models.Index(fields=['created_at'], name='community_c_created_e26abb_idx'),
        ),
        migrations.AddIndex(
            model_name='communitynotification',
            index=models.Index(fields=['is_read'], name='community_c_is_read_7bdde1_idx'),
        ),
        migrations.AddIndex(
            model_name='communitynotification',
            index=models.Index(fields=['notification_type'], name='community_c_notific_bf54f1_idx'),
        ),
        migrations.AddIndex(
            model_name='communitynotification',
            index=models.Index(fields=['priority'], name='community_c_priorit_b7f2e7_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymembership',
            index=models.Index(fields=['user'], name='community_c_user_id_01f08d_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymembership',
            index=models.Index(fields=['group'], name='community_c_group_i_c329e1_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymembership',
            index=models.Index(fields=['role'], name='community_c_role_94529a_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymembership',
            index=models.Index(fields=['status'], name='community_c_status_8253ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='communitymembership',
            unique_together={('user', 'group')},
        ),
        migrations.AddIndex(
            model_name='communitygroup',
            index=models.Index(fields=['name'], name='community_c_name_003701_idx'),
        ),
        migrations.AddIndex(
            model_name='communitygroup',
            index=models.Index(fields=['group_type'], name='community_c_group_t_2ea9c2_idx'),
        ),
        migrations.AddIndex(
            model_name='communitygroup',
            index=models.Index(fields=['is_private'], name='community_c_is_priv_8ef80a_idx'),
        ),
        migrations.AddIndex(
            model_name='communityevent',
            index=models.Index(fields=['group'], name='community_c_group_i_a7d6b1_idx'),
        ),
        migrations.AddIndex(
            model_name='communityevent',
            index=models.Index(fields=['creator'], name='community_c_creator_a040eb_idx'),
        ),
        migrations.AddIndex(
            model_name='communityevent',
            index=models.Index(fields=['start_time'], name='community_c_start_t_ee5ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='communityevent',
            index=models.Index(fields=['status'], name='community_c_status_185a37_idx'),
        ),
        migrations.AddIndex(
            model_name='communityevent',
            index=models.Index(fields=['location_type'], name='community_c_locatio_69daf8_idx'),
        ),
        migrations.AddIndex(
            model_name='communitycomment',
            index=models.Index(fields=['post'], name='community_c_post_id_2e8374_idx'),
        ),
        migrations.AddIndex(
            model_name='communitycomment',
            index=models.Index(fields=['author'], name='community_c_author__e0b77f_idx'),
        ),
        migrations.AddIndex(
            model_name='communitycomment',
            index=models.Index(fields=['created_at'], name='community_c_created_f09b31_idx'),
        ),
        migrations.AddIndex(
            model_name='communitycomment',
            index=models.Index(fields=['status'], name='community_c_status_8531db_idx'),
        ),
        migrations.AddIndex(
            model_name='communitycomment',
            index=models.Index(fields=['parent'], name='community_c_parent__a9de4f_idx'),
        ),
    ]
