# Generated by Django 4.2.7 on 2025-07-22 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('healthcare', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wearableintegration',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='healthcare_wearable_integrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vital_signs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='medical_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='healthcare.medicalrecord'),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='related_to_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condition_vitals', to='healthcare.condition'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_treatments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treatment',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='healthcare.medicalrecord'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='provider',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'provider'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provided_treatments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treatment',
            name='related_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condition_treatments', to='healthcare.condition'),
        ),
        migrations.AddField(
            model_name='symptom',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='healthcare.condition'),
        ),
        migrations.AddField(
            model_name='symptom',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_symptoms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralnetwork',
            name='provider',
            field=models.ForeignKey(limit_choices_to={'role': 'provider'}, on_delete=django.db.models.deletion.CASCADE, related_name='referral_specialties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralnetwork',
            name='specific_conditions',
            field=models.ManyToManyField(blank=True, related_name='specialist_providers', to='healthcare.rareconditionregistry'),
        ),
        migrations.AddField(
            model_name='medicationintake',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='healthcare.medication'),
        ),
        migrations.AddField(
            model_name='medicationintake',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medication',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='healthcare_created_medications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medication',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healthcare_medications', to='healthcare.medicalrecord'),
        ),
        migrations.AddField(
            model_name='medication',
            name='prescriber',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'provider'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='healthcare_prescribed_medications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medical_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='primary_physician',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'provider'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_medical_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labtest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lab_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labtest',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='healthcare.medicalrecord'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='ordered_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'provider'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_lab_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labtest',
            name='related_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_lab_tests', to='healthcare.condition'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lab_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labresult',
            name='interpreted_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'provider'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interpreted_lab_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labresult',
            name='lab_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='healthcare.labtest'),
        ),
        migrations.AddField(
            model_name='immunization',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_immunizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='immunization',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immunizations', to='healthcare.medicalrecord'),
        ),
        migrations.AddField(
            model_name='healthdataconsent',
            name='authorized_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorized_health_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='healthdataconsent',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='health_data_consents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='healthdataauditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_data_access_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familyhistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_family_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familyhistory',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_history', to='healthcare.medicalrecord'),
        ),
        migrations.AddField(
            model_name='familyhistory',
            name='rare_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_history_entries', to='healthcare.rareconditionregistry'),
        ),
        migrations.AddField(
            model_name='ehrintegration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ehr_integrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ehrintegration',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='ehr_integrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conditionflare',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flares', to='healthcare.condition'),
        ),
        migrations.AddField(
            model_name='conditionflare',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='condition',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conditions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='condition',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='healthcare.medicalrecord'),
        ),
        migrations.AddField(
            model_name='condition',
            name='rare_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_conditions', to='healthcare.rareconditionregistry'),
        ),
        migrations.AddField(
            model_name='allergy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_allergies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allergy',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='healthcare.medicalrecord'),
        ),
        migrations.AlterUniqueTogether(
            name='healthdataconsent',
            unique_together={('patient', 'consent_type', 'authorized_entity')},
        ),
    ]
