# Generated by Django 4.2.7 on 2025-07-31 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0002_geneticanalysis_geneticriskfactor'),
        ('healthcare', '0002_initial'),
    ]

    operations = [
    ]
