# Generated by Django 4.2.7 on 2025-07-22 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerabilityassessment',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='security.vulnerabilityassessment'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securitythreat',
            name='affected_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_threats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securitythreat',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_threats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securitythreat',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_threats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityincident',
            name='affected_users',
            field=models.ManyToManyField(blank=True, related_name='security_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityincident',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityincident',
            name='related_threats',
            field=models.ManyToManyField(blank=True, to='security.securitythreat'),
        ),
        migrations.AddField(
            model_name='securityincident',
            name='related_vulnerabilities',
            field=models.ManyToManyField(blank=True, to='security.vulnerability'),
        ),
        migrations.AddField(
            model_name='securityincident',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityincident',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='incident_team_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityconfiguration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='networkmonitor',
            index=models.Index(fields=['alert_type'], name='security_ne_alert_t_ecfedc_idx'),
        ),
        migrations.AddIndex(
            model_name='networkmonitor',
            index=models.Index(fields=['source_ip'], name='security_ne_source__aa59b4_idx'),
        ),
        migrations.AddIndex(
            model_name='networkmonitor',
            index=models.Index(fields=['timestamp'], name='security_ne_timesta_311051_idx'),
        ),
        migrations.AddIndex(
            model_name='networkmonitor',
            index=models.Index(fields=['severity'], name='security_ne_severit_5074cb_idx'),
        ),
        migrations.AddIndex(
            model_name='fileintegritymonitor',
            index=models.Index(fields=['file_path'], name='security_fi_file_pa_aa592c_idx'),
        ),
        migrations.AddIndex(
            model_name='fileintegritymonitor',
            index=models.Index(fields=['change_type'], name='security_fi_change__7ac420_idx'),
        ),
        migrations.AddIndex(
            model_name='fileintegritymonitor',
            index=models.Index(fields=['timestamp'], name='security_fi_timesta_881a29_idx'),
        ),
        migrations.AddIndex(
            model_name='fileintegritymonitor',
            index=models.Index(fields=['is_critical_file'], name='security_fi_is_crit_0677d1_idx'),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='vulnerabilityassessment',
            index=models.Index(fields=['scan_type'], name='security_vu_scan_ty_e21bb7_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerabilityassessment',
            index=models.Index(fields=['status'], name='security_vu_status_e983c8_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerabilityassessment',
            index=models.Index(fields=['started_at'], name='security_vu_started_441f6a_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerabilityassessment',
            index=models.Index(fields=['target'], name='security_vu_target_918025_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['severity'], name='security_vu_severit_13f2ee_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['status'], name='security_vu_status_003845_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['cve_id'], name='security_vu_cve_id_d25b5d_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['first_discovered'], name='security_vu_first_d_f17677_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['assessment'], name='security_vu_assessm_4e6cc2_idx'),
        ),
        migrations.AddIndex(
            model_name='securitythreat',
            index=models.Index(fields=['threat_type'], name='security_se_threat__18e166_idx'),
        ),
        migrations.AddIndex(
            model_name='securitythreat',
            index=models.Index(fields=['severity'], name='security_se_severit_4a54c3_idx'),
        ),
        migrations.AddIndex(
            model_name='securitythreat',
            index=models.Index(fields=['status'], name='security_se_status_04a34f_idx'),
        ),
        migrations.AddIndex(
            model_name='securitythreat',
            index=models.Index(fields=['detection_time'], name='security_se_detecti_945c25_idx'),
        ),
        migrations.AddIndex(
            model_name='securitythreat',
            index=models.Index(fields=['source_ip'], name='security_se_source__cebcd5_idx'),
        ),
        migrations.AddIndex(
            model_name='securitythreat',
            index=models.Index(fields=['affected_user'], name='security_se_affecte_b2cc75_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['incident_type'], name='security_se_inciden_ee2707_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['priority'], name='security_se_priorit_79f929_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['status'], name='security_se_status_9d6acf_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['reported_at'], name='security_se_reporte_b7bca8_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['incident_id'], name='security_se_inciden_86b793_idx'),
        ),
        migrations.AddIndex(
            model_name='securityconfiguration',
            index=models.Index(fields=['config_type'], name='security_se_config__99db54_idx'),
        ),
        migrations.AddIndex(
            model_name='securityconfiguration',
            index=models.Index(fields=['is_active'], name='security_se_is_acti_4ba4ed_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereport',
            index=models.Index(fields=['report_type'], name='security_co_report__878419_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereport',
            index=models.Index(fields=['generated_at'], name='security_co_generat_f3c818_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereport',
            index=models.Index(fields=['status'], name='security_co_status_87b164_idx'),
        ),
    ]
