# Generated by Django 4.2.7 on 2025-08-13 20:23

from django.db import migrations
import healthcare.fields


class Migration(migrations.Migration):

    dependencies = [
        ('telemedicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='host_key',
            field=healthcare.fields.EncryptedCharField(blank=True, null=True, max_length=100),
        ),
    ]
