# Generated by Django 4.2.7 on 2025-08-16 16:04

from django.db import migrations
import healthcare.fields


class Migration(migrations.Migration):

    dependencies = [
        ('telemedicine', '0002_auto_20250813_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='host_key',
            field=healthcare.fields.EncryptedCharField(blank=True),
        ),
    ]
