# Generated by Django 4.2.7 on 2025-07-22 04:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('access', 'Access'), ('error', 'Error'), ('password_reset', 'Password Reset'), ('account_lockout', 'Account Lockout'), ('permission_change', 'Permission Change'), ('export', 'Export'), ('share', 'Share')], db_index=True, max_length=20)),
                ('resource_type', models.CharField(db_index=True, max_length=100)),
                ('resource_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Audit Event',
                'verbose_name_plural': 'Audit Events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuditExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('file_url', models.URLField(blank=True)),
                ('filters', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Audit Export',
                'verbose_name_plural': 'Audit Exports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('daily_audit', 'Daily Audit'), ('phi_access', 'PHI Access'), ('security_incidents', 'Security Incidents'), ('user_activity', 'User Activity'), ('system_access', 'System Access'), ('weekly_audit', 'Weekly Audit'), ('monthly_audit', 'Monthly Audit'), ('quarterly_audit', 'Quarterly Audit'), ('annual_audit', 'Annual Audit'), ('custom', 'Custom Report')], db_index=True, max_length=30)),
                ('report_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('file_url', models.URLField(blank=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compliance Report',
                'verbose_name_plural': 'Compliance Reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='PHIAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_type', models.CharField(choices=[('view', 'View'), ('modify', 'Modify'), ('export', 'Export'), ('share', 'Share'), ('print', 'Print')], db_index=True, max_length=20)),
                ('reason', models.TextField(help_text='HIPAA requires a documented reason for accessing PHI')),
                ('record_type', models.CharField(db_index=True, max_length=100)),
                ('record_id', models.CharField(db_index=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'PHI Access Log',
                'verbose_name_plural': 'PHI Access Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('failed_login', 'Failed Login'), ('successful_login', 'Successful Login'), ('suspicious_login', 'Suspicious Login'), ('unusual_access', 'Unusual Access Pattern'), ('permission_violation', 'Permission Violation'), ('brute_force_attempt', 'Brute Force Attempt'), ('unusual_activity', 'Unusual Activity'), ('system_error', 'System Error'), ('auth_failure', 'Authentication Failure'), ('auth_success', 'Authentication Success'), ('account_locked', 'Account Locked'), ('data_export', 'Data Export'), ('bulk_access', 'Bulk Data Access'), ('after_hours_access', 'After Hours Access'), ('vip_access', 'VIP Record Access'), ('security_change', 'Security Setting Change'), ('api_key_usage', 'API Key Usage'), ('rapid_access', 'Rapid Access Pattern'), ('unauthorized_access', 'Unauthorized Access'), ('data_breach', 'Data Breach'), ('malware_detected', 'Malware Detected'), ('system_intrusion', 'System Intrusion'), ('privilege_escalation', 'Privilege Escalation'), ('data_exfiltration', 'Data Exfiltration')], db_index=True, max_length=30)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Security Audit Log',
                'verbose_name_plural': 'Security Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
