# Generated by Django 4.2.7 on 2025-07-22 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityauditlog',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_security_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityauditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phiaccesslog',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phi_accessed_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phiaccesslog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phi_access_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_compliance_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditexport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_exports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['event_type'], name='audit_secur_event_t_b54f0b_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['severity'], name='audit_secur_severit_ac6cb9_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['resolved'], name='audit_secur_resolve_50e073_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['timestamp'], name='audit_secur_timesta_873d0a_idx'),
        ),
        migrations.AddIndex(
            model_name='phiaccesslog',
            index=models.Index(fields=['access_type'], name='audit_phiac_access__75b314_idx'),
        ),
        migrations.AddIndex(
            model_name='phiaccesslog',
            index=models.Index(fields=['user'], name='audit_phiac_user_id_f1ff0d_idx'),
        ),
        migrations.AddIndex(
            model_name='phiaccesslog',
            index=models.Index(fields=['patient'], name='audit_phiac_patient_f88437_idx'),
        ),
        migrations.AddIndex(
            model_name='phiaccesslog',
            index=models.Index(fields=['timestamp'], name='audit_phiac_timesta_1fc211_idx'),
        ),
        migrations.AddIndex(
            model_name='phiaccesslog',
            index=models.Index(fields=['record_type', 'record_id'], name='audit_phiac_record__6cda84_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereport',
            index=models.Index(fields=['report_type'], name='audit_compl_report__481012_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereport',
            index=models.Index(fields=['report_date'], name='audit_compl_report__c62915_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereport',
            index=models.Index(fields=['status'], name='audit_compl_status_3f355e_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereport',
            index=models.Index(fields=['created_at'], name='audit_compl_created_3db656_idx'),
        ),
        migrations.AddIndex(
            model_name='auditexport',
            index=models.Index(fields=['status'], name='audit_audit_status_7cd9d5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditexport',
            index=models.Index(fields=['user'], name='audit_audit_user_id_e12858_idx'),
        ),
        migrations.AddIndex(
            model_name='auditexport',
            index=models.Index(fields=['created_at'], name='audit_audit_created_830698_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['event_type'], name='audit_audit_event_t_04511c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['resource_type'], name='audit_audit_resourc_0c5eb7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['user'], name='audit_audit_user_id_c5b9b3_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['timestamp'], name='audit_audit_timesta_ee9c56_idx'),
        ),
    ]
