# Generated by Django 4.2.7 on 2025-07-22 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fhir', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fhirpractitioner',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Link to Django User model', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fhir_practitioner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fhirpatient',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Link to Django User model', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fhir_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fhirorganization',
            name='part_of',
            field=models.ForeignKey(blank=True, help_text='The organization of which this organization forms a part', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_organizations', to='fhir.fhirorganization'),
        ),
        migrations.AddField(
            model_name='fhirobservation',
            name='patient',
            field=models.ForeignKey(help_text='Patient this observation is about', on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='fhir.fhirpatient'),
        ),
        migrations.AddField(
            model_name='fhirmedicationstatement',
            name='patient',
            field=models.ForeignKey(help_text='Patient who is taking the medication', on_delete=django.db.models.deletion.CASCADE, related_name='medication_statements', to='fhir.fhirpatient'),
        ),
        migrations.AddField(
            model_name='fhirencounter',
            name='patient',
            field=models.ForeignKey(help_text='Patient involved in the encounter', on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='fhir.fhirpatient'),
        ),
        migrations.AddField(
            model_name='fhircondition',
            name='patient',
            field=models.ForeignKey(help_text='Patient who has the condition', on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='fhir.fhirpatient'),
        ),
        migrations.AddField(
            model_name='fhircommunication',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='Patient involved in the communication', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='fhir.fhirpatient'),
        ),
        migrations.AddIndex(
            model_name='fhirpractitioner',
            index=models.Index(fields=['name'], name='fhir_fhirpr_name_af9587_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirpractitioner',
            index=models.Index(fields=['active'], name='fhir_fhirpr_active_04da6c_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirpatient',
            index=models.Index(fields=['name'], name='fhir_fhirpa_name_03fa00_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirpatient',
            index=models.Index(fields=['birth_date'], name='fhir_fhirpa_birth_d_8d7d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirpatient',
            index=models.Index(fields=['gender'], name='fhir_fhirpa_gender_e52094_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirorganization',
            index=models.Index(fields=['name'], name='fhir_fhiror_name_6b3113_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirorganization',
            index=models.Index(fields=['type'], name='fhir_fhiror_type_10a6c9_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirorganization',
            index=models.Index(fields=['active'], name='fhir_fhiror_active_34c8b4_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirobservation',
            index=models.Index(fields=['patient'], name='fhir_fhirob_patient_f0459f_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirobservation',
            index=models.Index(fields=['code'], name='fhir_fhirob_code_3fe587_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirobservation',
            index=models.Index(fields=['effective_date'], name='fhir_fhirob_effecti_d6dce9_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirobservation',
            index=models.Index(fields=['status'], name='fhir_fhirob_status_f95723_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirobservation',
            index=models.Index(fields=['category'], name='fhir_fhirob_categor_956068_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirobservation',
            index=models.Index(fields=['is_nmosd_indicator'], name='fhir_fhirob_is_nmos_3ce334_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirmedicationstatement',
            index=models.Index(fields=['patient'], name='fhir_fhirme_patient_f03a52_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirmedicationstatement',
            index=models.Index(fields=['medication'], name='fhir_fhirme_medicat_9a69d7_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirmedicationstatement',
            index=models.Index(fields=['status'], name='fhir_fhirme_status_28ce3d_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirmedicationstatement',
            index=models.Index(fields=['effective_date'], name='fhir_fhirme_effecti_5e70ab_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirmedicationstatement',
            index=models.Index(fields=['adherence_status'], name='fhir_fhirme_adheren_cd8530_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirencounter',
            index=models.Index(fields=['patient'], name='fhir_fhiren_patient_667744_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirencounter',
            index=models.Index(fields=['status'], name='fhir_fhiren_status_ba9956_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirencounter',
            index=models.Index(fields=['class_code'], name='fhir_fhiren_class_c_53e04b_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirencounter',
            index=models.Index(fields=['start'], name='fhir_fhiren_start_8f7c12_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirencounter',
            index=models.Index(fields=['is_telemedicine'], name='fhir_fhiren_is_tele_bdf4e9_idx'),
        ),
        migrations.AddIndex(
            model_name='fhircondition',
            index=models.Index(fields=['patient'], name='fhir_fhirco_patient_1b740a_idx'),
        ),
        migrations.AddIndex(
            model_name='fhircondition',
            index=models.Index(fields=['code'], name='fhir_fhirco_code_39542d_idx'),
        ),
        migrations.AddIndex(
            model_name='fhircondition',
            index=models.Index(fields=['clinical_status'], name='fhir_fhirco_clinica_09be12_idx'),
        ),
        migrations.AddIndex(
            model_name='fhircondition',
            index=models.Index(fields=['verification_status'], name='fhir_fhirco_verific_7ac71d_idx'),
        ),
        migrations.AddIndex(
            model_name='fhircondition',
            index=models.Index(fields=['is_nmosd'], name='fhir_fhirco_is_nmos_d5f3cf_idx'),
        ),
        migrations.AddIndex(
            model_name='fhircommunication',
            index=models.Index(fields=['patient'], name='fhir_fhirco_patient_466d13_idx'),
        ),
        migrations.AddIndex(
            model_name='fhircommunication',
            index=models.Index(fields=['sender'], name='fhir_fhirco_sender_1fb575_idx'),
        ),
        migrations.AddIndex(
            model_name='fhircommunication',
            index=models.Index(fields=['recipient'], name='fhir_fhirco_recipie_7c8154_idx'),
        ),
        migrations.AddIndex(
            model_name='fhircommunication',
            index=models.Index(fields=['status'], name='fhir_fhirco_status_514058_idx'),
        ),
        migrations.AddIndex(
            model_name='fhircommunication',
            index=models.Index(fields=['sent'], name='fhir_fhirco_sent_3f6c98_idx'),
        ),
        migrations.AddIndex(
            model_name='fhircommunication',
            index=models.Index(fields=['category'], name='fhir_fhirco_categor_c11d6e_idx'),
        ),
        migrations.AddIndex(
            model_name='fhircommunication',
            index=models.Index(fields=['medium'], name='fhir_fhirco_medium_2f59ea_idx'),
        ),
    ]
